// Upgrade NOTE: replaced 'mul(UNITY_MATRIX_MVP,*)' with 'UnityObjectToClipPos(*)'

Shader "Custom/NegativeColors" {
	SubShader {
		Tags {
			"Queue" = "Transparent"
			"IgnoreProjector" = "True"
			"RenderType" = "Opaque"
		}

		ZWrite On
		Lighting Off
		Cull Off
		Fog{ Mode Off }
		Blend One Zero

		GrabPass {}	// Grab pass to get texture behind material attached object

		Pass {
			CGPROGRAM

			#pragma vertex vert
			#pragma fragment frag
			#include "UnityCG.cginc"

			sampler2D _GrabTexture; // Automatically generated by the GrabPass

			struct vertInput{
				float4 vertex : POSITION;
			};

			struct vertOutput {
				float4 vertex : POSITION;
				float4 uvgrab : TEXCOORD1;
			};

			vertOutput vert(vertInput v) {
				vertOutput o;
				o.vertex = UnityObjectToClipPos(v.vertex);
				o.uvgrab = ComputeGrabScreenPos(o.vertex);	// grab screen texture
				return o;
			}

			half4 frag(vertOutput i) : COLOR {
				fixed4 col = tex2Dproj(_GrabTexture, UNITY_PROJ_COORD(i.uvgrab)); // Apply the screen texture in the correct position
				col = half4(1 - col.r, 1 - col.g, 1 - col.b, col.a); // Negative colors
				return col;
			}

			ENDCG
		}
	}
}
